hvt/hvt_module_net.o: hvt/hvt_module_net.c hvt/../common/tap_attach.h \
 hvt/hvt.h hvt/../common/cc.h hvt/../common/elf.h hvt/../common/mft.h \
 /home/dinosaure/dev/solo5-clean-release/include/mft_abi.h \
 /home/dinosaure/dev/solo5-clean-release/include/hvt_abi.h \
 /home/dinosaure/dev/solo5-clean-release/include/elf_abi.h hvt/hvt_gdb.h \
 /home/dinosaure/dev/solo5-clean-release/include/solo5.h \
 /home/dinosaure/dev/solo5-clean-release/include/hvt_ring.h hvt/hvt_kvm.h
hvt/../common/tap_attach.h:
hvt/hvt.h:
hvt/../common/cc.h:
hvt/../common/elf.h:
hvt/../common/mft.h:
/home/dinosaure/dev/solo5-clean-release/include/mft_abi.h:
/home/dinosaure/dev/solo5-clean-release/include/hvt_abi.h:
/home/dinosaure/dev/solo5-clean-release/include/elf_abi.h:
hvt/hvt_gdb.h:
/home/dinosaure/dev/solo5-clean-release/include/solo5.h:
/home/dinosaure/dev/solo5-clean-release/include/hvt_ring.h:
hvt/hvt_kvm.h:
