name: DragonFly
on:
  push:
  pull_request:

# Restrict the GITHUB_TOKEN
permissions: {}

jobs:
  Build:
    name: AMD64
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: DragonFly action
        id: test
        uses: vmactions/dragonflybsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y llvm18 gcc9
          run: |
            (set -x; clang18 -dD -E -P -x c /dev/null)
            printf '######################################################'
            (set -x; gcc9 -dD -E -P -x c /dev/null)
            printf '######################################################'
            (set -x; cc -dD -E -P -x c /dev/null)
